// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/logging/v2/log_entry.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// An individual entry in a log.
struct Google_Logging_V2_LogEntry {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The resource name of the log to which this log entry belongs:
  ///
  ///     "projects/[PROJECT_ID]/logs/[LOG_ID]"
  ///     "organizations/[ORGANIZATION_ID]/logs/[LOG_ID]"
  ///     "billingAccounts/[BILLING_ACCOUNT_ID]/logs/[LOG_ID]"
  ///     "folders/[FOLDER_ID]/logs/[LOG_ID]"
  ///
  /// A project number may be used in place of PROJECT_ID. The project number is
  /// translated to its corresponding PROJECT_ID internally and the `log_name`
  /// field will contain PROJECT_ID in queries and exports.
  ///
  /// `[LOG_ID]` must be URL-encoded within `log_name`. Example:
  /// `"organizations/1234567890/logs/cloudresourcemanager.googleapis.com%2Factivity"`.
  /// `[LOG_ID]` must be less than 512 characters long and can only include the
  /// following characters: upper and lower case alphanumeric characters,
  /// forward-slash, underscore, hyphen, and period.
  ///
  /// For backward compatibility, if `log_name` begins with a forward-slash, such
  /// as `/projects/...`, then the log entry is ingested as usual but the
  /// forward-slash is removed. Listing the log entry will not show the leading
  /// slash and filtering for a log name with a leading slash will never return
  /// any results.
  var logName: String {
    get {return _storage._logName}
    set {_uniqueStorage()._logName = newValue}
  }

  /// Required. The monitored resource that produced this log entry.
  ///
  /// Example: a log entry that reports a database error would be associated with
  /// the monitored resource designating the particular database that reported
  /// the error.
  var resource: Google_Api_MonitoredResource {
    get {return _storage._resource ?? Google_Api_MonitoredResource()}
    set {_uniqueStorage()._resource = newValue}
  }
  /// Returns true if `resource` has been explicitly set.
  var hasResource: Bool {return _storage._resource != nil}
  /// Clears the value of `resource`. Subsequent reads from it will return its default value.
  mutating func clearResource() {_uniqueStorage()._resource = nil}

  /// The log entry payload, which can be one of multiple types.
  var payload: OneOf_Payload? {
    get {return _storage._payload}
    set {_uniqueStorage()._payload = newValue}
  }

  /// The log entry payload, represented as a protocol buffer. Some Google
  /// Cloud Platform services use this field for their log entry payloads.
  ///
  /// The following protocol buffer types are supported; user-defined types
  /// are not supported:
  ///
  ///   "type.googleapis.com/google.cloud.audit.AuditLog"
  ///   "type.googleapis.com/google.appengine.logging.v1.RequestLog"
  var protoPayload: SwiftProtobuf.Google_Protobuf_Any {
    get {
      if case .protoPayload(let v)? = _storage._payload {return v}
      return SwiftProtobuf.Google_Protobuf_Any()
    }
    set {_uniqueStorage()._payload = .protoPayload(newValue)}
  }

  /// The log entry payload, represented as a Unicode string (UTF-8).
  var textPayload: String {
    get {
      if case .textPayload(let v)? = _storage._payload {return v}
      return String()
    }
    set {_uniqueStorage()._payload = .textPayload(newValue)}
  }

  /// The log entry payload, represented as a structure that is
  /// expressed as a JSON object.
  var jsonPayload: SwiftProtobuf.Google_Protobuf_Struct {
    get {
      if case .jsonPayload(let v)? = _storage._payload {return v}
      return SwiftProtobuf.Google_Protobuf_Struct()
    }
    set {_uniqueStorage()._payload = .jsonPayload(newValue)}
  }

  /// Optional. The time the event described by the log entry occurred. This time is used
  /// to compute the log entry's age and to enforce the logs retention period.
  /// If this field is omitted in a new log entry, then Logging assigns it the
  /// current time. Timestamps have nanosecond accuracy, but trailing zeros in
  /// the fractional seconds might be omitted when the timestamp is displayed.
  ///
  /// Incoming log entries must have timestamps that don't exceed the
  /// [logs retention
  /// period](https://cloud.google.com/logging/quotas#logs_retention_periods) in
  /// the past, and that don't exceed 24 hours in the future. Log entries outside
  /// those time boundaries aren't ingested by Logging.
  var timestamp: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._timestamp ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  var hasTimestamp: Bool {return _storage._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  mutating func clearTimestamp() {_uniqueStorage()._timestamp = nil}

  /// Output only. The time the log entry was received by Logging.
  var receiveTimestamp: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._receiveTimestamp ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._receiveTimestamp = newValue}
  }
  /// Returns true if `receiveTimestamp` has been explicitly set.
  var hasReceiveTimestamp: Bool {return _storage._receiveTimestamp != nil}
  /// Clears the value of `receiveTimestamp`. Subsequent reads from it will return its default value.
  mutating func clearReceiveTimestamp() {_uniqueStorage()._receiveTimestamp = nil}

  /// Optional. The severity of the log entry. The default value is `LogSeverity.DEFAULT`.
  var severity: Google_Logging_Type_LogSeverity {
    get {return _storage._severity}
    set {_uniqueStorage()._severity = newValue}
  }

  /// Optional. A unique identifier for the log entry. If you provide a value, then
  /// Logging considers other log entries in the same project, with the same
  /// `timestamp`, and with the same `insert_id` to be duplicates which are
  /// removed in a single query result. However, there are no guarantees of
  /// de-duplication in the export of logs.
  ///
  /// If the `insert_id` is omitted when writing a log entry, the Logging API
  ///  assigns its own unique identifier in this field.
  ///
  /// In queries, the `insert_id` is also used to order log entries that have
  /// the same `log_name` and `timestamp` values.
  var insertID: String {
    get {return _storage._insertID}
    set {_uniqueStorage()._insertID = newValue}
  }

  /// Optional. Information about the HTTP request associated with this log entry, if
  /// applicable.
  var httpRequest: Google_Logging_Type_HttpRequest {
    get {return _storage._httpRequest ?? Google_Logging_Type_HttpRequest()}
    set {_uniqueStorage()._httpRequest = newValue}
  }
  /// Returns true if `httpRequest` has been explicitly set.
  var hasHTTPRequest: Bool {return _storage._httpRequest != nil}
  /// Clears the value of `httpRequest`. Subsequent reads from it will return its default value.
  mutating func clearHTTPRequest() {_uniqueStorage()._httpRequest = nil}

  /// Optional. A set of user-defined (key, value) data that provides additional
  /// information about the log entry.
  var labels: Dictionary<String,String> {
    get {return _storage._labels}
    set {_uniqueStorage()._labels = newValue}
  }

  /// Optional. Information about an operation associated with the log entry, if
  /// applicable.
  var operation: Google_Logging_V2_LogEntryOperation {
    get {return _storage._operation ?? Google_Logging_V2_LogEntryOperation()}
    set {_uniqueStorage()._operation = newValue}
  }
  /// Returns true if `operation` has been explicitly set.
  var hasOperation: Bool {return _storage._operation != nil}
  /// Clears the value of `operation`. Subsequent reads from it will return its default value.
  mutating func clearOperation() {_uniqueStorage()._operation = nil}

  /// Optional. Resource name of the trace associated with the log entry, if any. If it
  /// contains a relative resource name, the name is assumed to be relative to
  /// `//tracing.googleapis.com`. Example:
  /// `projects/my-projectid/traces/06796866738c859f2f19b7cfb3214824`
  var trace: String {
    get {return _storage._trace}
    set {_uniqueStorage()._trace = newValue}
  }

  /// Optional. The span ID within the trace associated with the log entry.
  ///
  /// For Trace spans, this is the same format that the Trace API v2 uses: a
  /// 16-character hexadecimal encoding of an 8-byte array, such as
  /// `000000000000004a`.
  var spanID: String {
    get {return _storage._spanID}
    set {_uniqueStorage()._spanID = newValue}
  }

  /// Optional. The sampling decision of the trace associated with the log entry.
  ///
  /// True means that the trace resource name in the `trace` field was sampled
  /// for storage in a trace backend. False means that the trace was not sampled
  /// for storage when this log entry was written, or the sampling decision was
  /// unknown at the time. A non-sampled `trace` value is still useful as a
  /// request correlation identifier. The default is False.
  var traceSampled: Bool {
    get {return _storage._traceSampled}
    set {_uniqueStorage()._traceSampled = newValue}
  }

  /// Optional. Source code location information associated with the log entry, if any.
  var sourceLocation: Google_Logging_V2_LogEntrySourceLocation {
    get {return _storage._sourceLocation ?? Google_Logging_V2_LogEntrySourceLocation()}
    set {_uniqueStorage()._sourceLocation = newValue}
  }
  /// Returns true if `sourceLocation` has been explicitly set.
  var hasSourceLocation: Bool {return _storage._sourceLocation != nil}
  /// Clears the value of `sourceLocation`. Subsequent reads from it will return its default value.
  mutating func clearSourceLocation() {_uniqueStorage()._sourceLocation = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The log entry payload, which can be one of multiple types.
  enum OneOf_Payload: Equatable {
    /// The log entry payload, represented as a protocol buffer. Some Google
    /// Cloud Platform services use this field for their log entry payloads.
    ///
    /// The following protocol buffer types are supported; user-defined types
    /// are not supported:
    ///
    ///   "type.googleapis.com/google.cloud.audit.AuditLog"
    ///   "type.googleapis.com/google.appengine.logging.v1.RequestLog"
    case protoPayload(SwiftProtobuf.Google_Protobuf_Any)
    /// The log entry payload, represented as a Unicode string (UTF-8).
    case textPayload(String)
    /// The log entry payload, represented as a structure that is
    /// expressed as a JSON object.
    case jsonPayload(SwiftProtobuf.Google_Protobuf_Struct)

  #if !swift(>=4.1)
    static func ==(lhs: Google_Logging_V2_LogEntry.OneOf_Payload, rhs: Google_Logging_V2_LogEntry.OneOf_Payload) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.protoPayload, .protoPayload): return {
        guard case .protoPayload(let l) = lhs, case .protoPayload(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.textPayload, .textPayload): return {
        guard case .textPayload(let l) = lhs, case .textPayload(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.jsonPayload, .jsonPayload): return {
        guard case .jsonPayload(let l) = lhs, case .jsonPayload(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Additional information about a potentially long-running operation with which
/// a log entry is associated.
struct Google_Logging_V2_LogEntryOperation {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Optional. An arbitrary operation identifier. Log entries with the same
  /// identifier are assumed to be part of the same operation.
  var id: String = String()

  /// Optional. An arbitrary producer identifier. The combination of `id` and
  /// `producer` must be globally unique. Examples for `producer`:
  /// `"MyDivision.MyBigCompany.com"`, `"github.com/MyProject/MyApplication"`.
  var producer: String = String()

  /// Optional. Set this to True if this is the first log entry in the operation.
  var first: Bool = false

  /// Optional. Set this to True if this is the last log entry in the operation.
  var last: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Additional information about the source code location that produced the log
/// entry.
struct Google_Logging_V2_LogEntrySourceLocation {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Optional. Source file name. Depending on the runtime environment, this
  /// might be a simple name or a fully-qualified name.
  var file: String = String()

  /// Optional. Line within the source file. 1-based; 0 indicates no line number
  /// available.
  var line: Int64 = 0

  /// Optional. Human-readable name of the function or method being invoked, with
  /// optional context such as the class or package name. This information may be
  /// used in contexts such as the logs viewer, where a file and line number are
  /// less meaningful. The format can vary by language. For example:
  /// `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
  /// (Python).
  var function: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.logging.v2"

extension Google_Logging_V2_LogEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LogEntry"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    12: .standard(proto: "log_name"),
    8: .same(proto: "resource"),
    2: .standard(proto: "proto_payload"),
    3: .standard(proto: "text_payload"),
    6: .standard(proto: "json_payload"),
    9: .same(proto: "timestamp"),
    24: .standard(proto: "receive_timestamp"),
    10: .same(proto: "severity"),
    4: .standard(proto: "insert_id"),
    7: .standard(proto: "http_request"),
    11: .same(proto: "labels"),
    15: .same(proto: "operation"),
    22: .same(proto: "trace"),
    27: .standard(proto: "span_id"),
    30: .standard(proto: "trace_sampled"),
    23: .standard(proto: "source_location"),
  ]

  fileprivate class _StorageClass {
    var _logName: String = String()
    var _resource: Google_Api_MonitoredResource? = nil
    var _payload: Google_Logging_V2_LogEntry.OneOf_Payload?
    var _timestamp: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _receiveTimestamp: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _severity: Google_Logging_Type_LogSeverity = .default
    var _insertID: String = String()
    var _httpRequest: Google_Logging_Type_HttpRequest? = nil
    var _labels: Dictionary<String,String> = [:]
    var _operation: Google_Logging_V2_LogEntryOperation? = nil
    var _trace: String = String()
    var _spanID: String = String()
    var _traceSampled: Bool = false
    var _sourceLocation: Google_Logging_V2_LogEntrySourceLocation? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _logName = source._logName
      _resource = source._resource
      _payload = source._payload
      _timestamp = source._timestamp
      _receiveTimestamp = source._receiveTimestamp
      _severity = source._severity
      _insertID = source._insertID
      _httpRequest = source._httpRequest
      _labels = source._labels
      _operation = source._operation
      _trace = source._trace
      _spanID = source._spanID
      _traceSampled = source._traceSampled
      _sourceLocation = source._sourceLocation
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 2: try {
          var v: SwiftProtobuf.Google_Protobuf_Any?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .protoPayload(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .protoPayload(v)
          }
        }()
        case 3: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._payload != nil {try decoder.handleConflictingOneOf()}
            _storage._payload = .textPayload(v)
          }
        }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._insertID) }()
        case 6: try {
          var v: SwiftProtobuf.Google_Protobuf_Struct?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .jsonPayload(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .jsonPayload(v)
          }
        }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._httpRequest) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._resource) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._timestamp) }()
        case 10: try { try decoder.decodeSingularEnumField(value: &_storage._severity) }()
        case 11: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._labels) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._logName) }()
        case 15: try { try decoder.decodeSingularMessageField(value: &_storage._operation) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._trace) }()
        case 23: try { try decoder.decodeSingularMessageField(value: &_storage._sourceLocation) }()
        case 24: try { try decoder.decodeSingularMessageField(value: &_storage._receiveTimestamp) }()
        case 27: try { try decoder.decodeSingularStringField(value: &_storage._spanID) }()
        case 30: try { try decoder.decodeSingularBoolField(value: &_storage._traceSampled) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      switch _storage._payload {
      case .protoPayload?: try {
        guard case .protoPayload(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }()
      case .textPayload?: try {
        guard case .textPayload(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      }()
      default: break
      }
      if !_storage._insertID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._insertID, fieldNumber: 4)
      }
      try { if case .jsonPayload(let v)? = _storage._payload {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._httpRequest {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._resource {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._timestamp {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      if _storage._severity != .default {
        try visitor.visitSingularEnumField(value: _storage._severity, fieldNumber: 10)
      }
      if !_storage._labels.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._labels, fieldNumber: 11)
      }
      if !_storage._logName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._logName, fieldNumber: 12)
      }
      try { if let v = _storage._operation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      } }()
      if !_storage._trace.isEmpty {
        try visitor.visitSingularStringField(value: _storage._trace, fieldNumber: 22)
      }
      try { if let v = _storage._sourceLocation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 23)
      } }()
      try { if let v = _storage._receiveTimestamp {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 24)
      } }()
      if !_storage._spanID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._spanID, fieldNumber: 27)
      }
      if _storage._traceSampled != false {
        try visitor.visitSingularBoolField(value: _storage._traceSampled, fieldNumber: 30)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Logging_V2_LogEntry, rhs: Google_Logging_V2_LogEntry) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._logName != rhs_storage._logName {return false}
        if _storage._resource != rhs_storage._resource {return false}
        if _storage._payload != rhs_storage._payload {return false}
        if _storage._timestamp != rhs_storage._timestamp {return false}
        if _storage._receiveTimestamp != rhs_storage._receiveTimestamp {return false}
        if _storage._severity != rhs_storage._severity {return false}
        if _storage._insertID != rhs_storage._insertID {return false}
        if _storage._httpRequest != rhs_storage._httpRequest {return false}
        if _storage._labels != rhs_storage._labels {return false}
        if _storage._operation != rhs_storage._operation {return false}
        if _storage._trace != rhs_storage._trace {return false}
        if _storage._spanID != rhs_storage._spanID {return false}
        if _storage._traceSampled != rhs_storage._traceSampled {return false}
        if _storage._sourceLocation != rhs_storage._sourceLocation {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Logging_V2_LogEntryOperation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LogEntryOperation"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "producer"),
    3: .same(proto: "first"),
    4: .same(proto: "last"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.producer) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.first) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.last) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.producer.isEmpty {
      try visitor.visitSingularStringField(value: self.producer, fieldNumber: 2)
    }
    if self.first != false {
      try visitor.visitSingularBoolField(value: self.first, fieldNumber: 3)
    }
    if self.last != false {
      try visitor.visitSingularBoolField(value: self.last, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Logging_V2_LogEntryOperation, rhs: Google_Logging_V2_LogEntryOperation) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.producer != rhs.producer {return false}
    if lhs.first != rhs.first {return false}
    if lhs.last != rhs.last {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Logging_V2_LogEntrySourceLocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LogEntrySourceLocation"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "file"),
    2: .same(proto: "line"),
    3: .same(proto: "function"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.file) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.line) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.function) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.file.isEmpty {
      try visitor.visitSingularStringField(value: self.file, fieldNumber: 1)
    }
    if self.line != 0 {
      try visitor.visitSingularInt64Field(value: self.line, fieldNumber: 2)
    }
    if !self.function.isEmpty {
      try visitor.visitSingularStringField(value: self.function, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Logging_V2_LogEntrySourceLocation, rhs: Google_Logging_V2_LogEntrySourceLocation) -> Bool {
    if lhs.file != rhs.file {return false}
    if lhs.line != rhs.line {return false}
    if lhs.function != rhs.function {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
