//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: google/pubsub/v1/schema.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Service for doing schema-related operations.
///
/// Usage: instantiate `Google_Pubsub_V1_SchemaServiceClient`, then call methods of this protocol to make API calls.
internal protocol Google_Pubsub_V1_SchemaServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? { get }

  func createSchema(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema>

  func getSchema(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema>

  func listSchemas(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse>

  func deleteSchema(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func validateSchema(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse>

  func validateMessage(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse>
}

extension Google_Pubsub_V1_SchemaServiceClientProtocol {
  internal var serviceName: String {
    return "google.pubsub.v1.SchemaService"
  }

  /// Creates a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createSchema(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.createSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSchemaInterceptors() ?? []
    )
  }

  /// Gets a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getSchema(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.getSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSchemaInterceptors() ?? []
    )
  }

  /// Lists schemas in a project.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListSchemas.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listSchemas(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemas.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemasInterceptors() ?? []
    )
  }

  /// Deletes a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteSchema(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaInterceptors() ?? []
    )
  }

  /// Validates a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to ValidateSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func validateSchema(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateSchemaInterceptors() ?? []
    )
  }

  /// Validates a message against a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to ValidateMessage.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func validateMessage(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateMessage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateMessageInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Google_Pubsub_V1_SchemaServiceClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Google_Pubsub_V1_SchemaServiceNIOClient")
internal final class Google_Pubsub_V1_SchemaServiceClient: Google_Pubsub_V1_SchemaServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the google.pubsub.v1.SchemaService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Google_Pubsub_V1_SchemaServiceNIOClient: Google_Pubsub_V1_SchemaServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the google.pubsub.v1.SchemaService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Service for doing schema-related operations.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Google_Pubsub_V1_SchemaServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? { get }

  func makeCreateSchemaCall(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema>

  func makeGetSchemaCall(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema>

  func makeListSchemasCall(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse>

  func makeDeleteSchemaCall(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func makeValidateSchemaCall(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse>

  func makeValidateMessageCall(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Pubsub_V1_SchemaServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Pubsub_V1_SchemaServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeCreateSchemaCall(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.createSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSchemaInterceptors() ?? []
    )
  }

  internal func makeGetSchemaCall(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.getSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSchemaInterceptors() ?? []
    )
  }

  internal func makeListSchemasCall(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemas.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemasInterceptors() ?? []
    )
  }

  internal func makeDeleteSchemaCall(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaInterceptors() ?? []
    )
  }

  internal func makeValidateSchemaCall(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateSchemaInterceptors() ?? []
    )
  }

  internal func makeValidateMessageCall(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateMessage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateMessageInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Pubsub_V1_SchemaServiceAsyncClientProtocol {
  internal func createSchema(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_Schema {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.createSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSchemaInterceptors() ?? []
    )
  }

  internal func getSchema(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_Schema {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.getSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSchemaInterceptors() ?? []
    )
  }

  internal func listSchemas(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_ListSchemasResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemas.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemasInterceptors() ?? []
    )
  }

  internal func deleteSchema(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaInterceptors() ?? []
    )
  }

  internal func validateSchema(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_ValidateSchemaResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateSchemaInterceptors() ?? []
    )
  }

  internal func validateMessage(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_ValidateMessageResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateMessage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateMessageInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Google_Pubsub_V1_SchemaServiceAsyncClient: Google_Pubsub_V1_SchemaServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'createSchema'.
  func makeCreateSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when invoking 'getSchema'.
  func makeGetSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when invoking 'listSchemas'.
  func makeListSchemasInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteSchema'.
  func makeDeleteSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'validateSchema'.
  func makeValidateSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse>]

  /// - Returns: Interceptors to use when invoking 'validateMessage'.
  func makeValidateMessageInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse>]
}

internal enum Google_Pubsub_V1_SchemaServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "SchemaService",
    fullName: "google.pubsub.v1.SchemaService",
    methods: [
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.createSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.getSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemas,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateMessage,
    ]
  )

  internal enum Methods {
    internal static let createSchema = GRPCMethodDescriptor(
      name: "CreateSchema",
      path: "/google.pubsub.v1.SchemaService/CreateSchema",
      type: GRPCCallType.unary
    )

    internal static let getSchema = GRPCMethodDescriptor(
      name: "GetSchema",
      path: "/google.pubsub.v1.SchemaService/GetSchema",
      type: GRPCCallType.unary
    )

    internal static let listSchemas = GRPCMethodDescriptor(
      name: "ListSchemas",
      path: "/google.pubsub.v1.SchemaService/ListSchemas",
      type: GRPCCallType.unary
    )

    internal static let deleteSchema = GRPCMethodDescriptor(
      name: "DeleteSchema",
      path: "/google.pubsub.v1.SchemaService/DeleteSchema",
      type: GRPCCallType.unary
    )

    internal static let validateSchema = GRPCMethodDescriptor(
      name: "ValidateSchema",
      path: "/google.pubsub.v1.SchemaService/ValidateSchema",
      type: GRPCCallType.unary
    )

    internal static let validateMessage = GRPCMethodDescriptor(
      name: "ValidateMessage",
      path: "/google.pubsub.v1.SchemaService/ValidateMessage",
      type: GRPCCallType.unary
    )
  }
}

