//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: google/cloud/aiplatform/v1/feature_online_store_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// A service for fetching feature values from the online store.
///
/// Usage: instantiate `Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClient`, then call methods of this protocol to make API calls.
public protocol Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol? { get }

  func fetchFeatureValues(
    _ request: Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest, Google_Cloud_Aiplatform_V1_FetchFeatureValuesResponse>

  func searchNearestEntities(
    _ request: Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest, Google_Cloud_Aiplatform_V1_SearchNearestEntitiesResponse>
}

extension Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientProtocol {
  public var serviceName: String {
    return "google.cloud.aiplatform.v1.FeatureOnlineStoreService"
  }

  /// Fetch feature values under a FeatureView.
  ///
  /// - Parameters:
  ///   - request: Request to send to FetchFeatureValues.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func fetchFeatureValues(
    _ request: Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest, Google_Cloud_Aiplatform_V1_FetchFeatureValuesResponse> {
    return self.makeUnaryCall(
      path: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.Methods.fetchFeatureValues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFetchFeatureValuesInterceptors() ?? []
    )
  }

  /// Search the nearest entities under a FeatureView.
  /// Search only works for indexable feature view; if a feature view isn't
  /// indexable, returns Invalid argument response.
  ///
  /// - Parameters:
  ///   - request: Request to send to SearchNearestEntities.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func searchNearestEntities(
    _ request: Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest, Google_Cloud_Aiplatform_V1_SearchNearestEntitiesResponse> {
    return self.makeUnaryCall(
      path: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.Methods.searchNearestEntities.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchNearestEntitiesInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceNIOClient")
public final class Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClient: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the google.cloud.aiplatform.v1.FeatureOnlineStoreService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceNIOClient: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the google.cloud.aiplatform.v1.FeatureOnlineStoreService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// A service for fetching feature values from the online store.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol? { get }

  func makeFetchFeatureValuesCall(
    _ request: Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest, Google_Cloud_Aiplatform_V1_FetchFeatureValuesResponse>

  func makeSearchNearestEntitiesCall(
    _ request: Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest, Google_Cloud_Aiplatform_V1_SearchNearestEntitiesResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeFetchFeatureValuesCall(
    _ request: Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest, Google_Cloud_Aiplatform_V1_FetchFeatureValuesResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.Methods.fetchFeatureValues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFetchFeatureValuesInterceptors() ?? []
    )
  }

  public func makeSearchNearestEntitiesCall(
    _ request: Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest, Google_Cloud_Aiplatform_V1_SearchNearestEntitiesResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.Methods.searchNearestEntities.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchNearestEntitiesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceAsyncClientProtocol {
  public func fetchFeatureValues(
    _ request: Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Cloud_Aiplatform_V1_FetchFeatureValuesResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.Methods.fetchFeatureValues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFetchFeatureValuesInterceptors() ?? []
    )
  }

  public func searchNearestEntities(
    _ request: Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Cloud_Aiplatform_V1_SearchNearestEntitiesResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.Methods.searchNearestEntities.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchNearestEntitiesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceAsyncClient: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'fetchFeatureValues'.
  func makeFetchFeatureValuesInterceptors() -> [ClientInterceptor<Google_Cloud_Aiplatform_V1_FetchFeatureValuesRequest, Google_Cloud_Aiplatform_V1_FetchFeatureValuesResponse>]

  /// - Returns: Interceptors to use when invoking 'searchNearestEntities'.
  func makeSearchNearestEntitiesInterceptors() -> [ClientInterceptor<Google_Cloud_Aiplatform_V1_SearchNearestEntitiesRequest, Google_Cloud_Aiplatform_V1_SearchNearestEntitiesResponse>]
}

public enum Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "FeatureOnlineStoreService",
    fullName: "google.cloud.aiplatform.v1.FeatureOnlineStoreService",
    methods: [
      Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.Methods.fetchFeatureValues,
      Google_Cloud_Aiplatform_V1_FeatureOnlineStoreServiceClientMetadata.Methods.searchNearestEntities,
    ]
  )

  public enum Methods {
    public static let fetchFeatureValues = GRPCMethodDescriptor(
      name: "FetchFeatureValues",
      path: "/google.cloud.aiplatform.v1.FeatureOnlineStoreService/FetchFeatureValues",
      type: GRPCCallType.unary
    )

    public static let searchNearestEntities = GRPCMethodDescriptor(
      name: "SearchNearestEntities",
      path: "/google.cloud.aiplatform.v1.FeatureOnlineStoreService/SearchNearestEntities",
      type: GRPCCallType.unary
    )
  }
}

