//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: google/cloud/aiplatform/v1/specialist_pool_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// A service for creating and managing Customer SpecialistPools.
/// When customers start Data Labeling jobs, they can reuse/create Specialist
/// Pools to bring their own Specialists to label the data.
/// Customers can add/remove Managers for the Specialist Pool on Cloud console,
/// then Managers will get email notifications to manage Specialists and tasks on
/// CrowdCompute console.
///
/// Usage: instantiate `Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClient`, then call methods of this protocol to make API calls.
public protocol Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol? { get }

  func createSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest, Google_Longrunning_Operation>

  func getSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest, Google_Cloud_Aiplatform_V1_SpecialistPool>

  func listSpecialistPools(
    _ request: Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest, Google_Cloud_Aiplatform_V1_ListSpecialistPoolsResponse>

  func deleteSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest, Google_Longrunning_Operation>

  func updateSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest, Google_Longrunning_Operation>
}

extension Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientProtocol {
  public var serviceName: String {
    return "google.cloud.aiplatform.v1.SpecialistPoolService"
  }

  /// Creates a SpecialistPool.
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateSpecialistPool.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest, Google_Longrunning_Operation> {
    return self.makeUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.createSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSpecialistPoolInterceptors() ?? []
    )
  }

  /// Gets a SpecialistPool.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetSpecialistPool.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest, Google_Cloud_Aiplatform_V1_SpecialistPool> {
    return self.makeUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.getSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSpecialistPoolInterceptors() ?? []
    )
  }

  /// Lists SpecialistPools in a Location.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListSpecialistPools.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listSpecialistPools(
    _ request: Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest, Google_Cloud_Aiplatform_V1_ListSpecialistPoolsResponse> {
    return self.makeUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.listSpecialistPools.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSpecialistPoolsInterceptors() ?? []
    )
  }

  /// Deletes a SpecialistPool as well as all Specialists in the pool.
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteSpecialistPool.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deleteSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest, Google_Longrunning_Operation> {
    return self.makeUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.deleteSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSpecialistPoolInterceptors() ?? []
    )
  }

  /// Updates a SpecialistPool.
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateSpecialistPool.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updateSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest, Google_Longrunning_Operation> {
    return self.makeUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.updateSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateSpecialistPoolInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Google_Cloud_Aiplatform_V1_SpecialistPoolServiceNIOClient")
public final class Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClient: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the google.cloud.aiplatform.v1.SpecialistPoolService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Google_Cloud_Aiplatform_V1_SpecialistPoolServiceNIOClient: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the google.cloud.aiplatform.v1.SpecialistPoolService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// A service for creating and managing Customer SpecialistPools.
/// When customers start Data Labeling jobs, they can reuse/create Specialist
/// Pools to bring their own Specialists to label the data.
/// Customers can add/remove Managers for the Specialist Pool on Cloud console,
/// then Managers will get email notifications to manage Specialists and tasks on
/// CrowdCompute console.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Google_Cloud_Aiplatform_V1_SpecialistPoolServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol? { get }

  func makeCreateSpecialistPoolCall(
    _ request: Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest, Google_Longrunning_Operation>

  func makeGetSpecialistPoolCall(
    _ request: Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest, Google_Cloud_Aiplatform_V1_SpecialistPool>

  func makeListSpecialistPoolsCall(
    _ request: Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest, Google_Cloud_Aiplatform_V1_ListSpecialistPoolsResponse>

  func makeDeleteSpecialistPoolCall(
    _ request: Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest, Google_Longrunning_Operation>

  func makeUpdateSpecialistPoolCall(
    _ request: Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest, Google_Longrunning_Operation>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Cloud_Aiplatform_V1_SpecialistPoolServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeCreateSpecialistPoolCall(
    _ request: Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest, Google_Longrunning_Operation> {
    return self.makeAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.createSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSpecialistPoolInterceptors() ?? []
    )
  }

  public func makeGetSpecialistPoolCall(
    _ request: Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest, Google_Cloud_Aiplatform_V1_SpecialistPool> {
    return self.makeAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.getSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSpecialistPoolInterceptors() ?? []
    )
  }

  public func makeListSpecialistPoolsCall(
    _ request: Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest, Google_Cloud_Aiplatform_V1_ListSpecialistPoolsResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.listSpecialistPools.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSpecialistPoolsInterceptors() ?? []
    )
  }

  public func makeDeleteSpecialistPoolCall(
    _ request: Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest, Google_Longrunning_Operation> {
    return self.makeAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.deleteSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSpecialistPoolInterceptors() ?? []
    )
  }

  public func makeUpdateSpecialistPoolCall(
    _ request: Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest, Google_Longrunning_Operation> {
    return self.makeAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.updateSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateSpecialistPoolInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Cloud_Aiplatform_V1_SpecialistPoolServiceAsyncClientProtocol {
  public func createSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Longrunning_Operation {
    return try await self.performAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.createSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSpecialistPoolInterceptors() ?? []
    )
  }

  public func getSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Cloud_Aiplatform_V1_SpecialistPool {
    return try await self.performAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.getSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSpecialistPoolInterceptors() ?? []
    )
  }

  public func listSpecialistPools(
    _ request: Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Cloud_Aiplatform_V1_ListSpecialistPoolsResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.listSpecialistPools.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSpecialistPoolsInterceptors() ?? []
    )
  }

  public func deleteSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Longrunning_Operation {
    return try await self.performAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.deleteSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSpecialistPoolInterceptors() ?? []
    )
  }

  public func updateSpecialistPool(
    _ request: Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Longrunning_Operation {
    return try await self.performAsyncUnaryCall(
      path: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.updateSpecialistPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateSpecialistPoolInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Google_Cloud_Aiplatform_V1_SpecialistPoolServiceAsyncClient: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'createSpecialistPool'.
  func makeCreateSpecialistPoolInterceptors() -> [ClientInterceptor<Google_Cloud_Aiplatform_V1_CreateSpecialistPoolRequest, Google_Longrunning_Operation>]

  /// - Returns: Interceptors to use when invoking 'getSpecialistPool'.
  func makeGetSpecialistPoolInterceptors() -> [ClientInterceptor<Google_Cloud_Aiplatform_V1_GetSpecialistPoolRequest, Google_Cloud_Aiplatform_V1_SpecialistPool>]

  /// - Returns: Interceptors to use when invoking 'listSpecialistPools'.
  func makeListSpecialistPoolsInterceptors() -> [ClientInterceptor<Google_Cloud_Aiplatform_V1_ListSpecialistPoolsRequest, Google_Cloud_Aiplatform_V1_ListSpecialistPoolsResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteSpecialistPool'.
  func makeDeleteSpecialistPoolInterceptors() -> [ClientInterceptor<Google_Cloud_Aiplatform_V1_DeleteSpecialistPoolRequest, Google_Longrunning_Operation>]

  /// - Returns: Interceptors to use when invoking 'updateSpecialistPool'.
  func makeUpdateSpecialistPoolInterceptors() -> [ClientInterceptor<Google_Cloud_Aiplatform_V1_UpdateSpecialistPoolRequest, Google_Longrunning_Operation>]
}

public enum Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "SpecialistPoolService",
    fullName: "google.cloud.aiplatform.v1.SpecialistPoolService",
    methods: [
      Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.createSpecialistPool,
      Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.getSpecialistPool,
      Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.listSpecialistPools,
      Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.deleteSpecialistPool,
      Google_Cloud_Aiplatform_V1_SpecialistPoolServiceClientMetadata.Methods.updateSpecialistPool,
    ]
  )

  public enum Methods {
    public static let createSpecialistPool = GRPCMethodDescriptor(
      name: "CreateSpecialistPool",
      path: "/google.cloud.aiplatform.v1.SpecialistPoolService/CreateSpecialistPool",
      type: GRPCCallType.unary
    )

    public static let getSpecialistPool = GRPCMethodDescriptor(
      name: "GetSpecialistPool",
      path: "/google.cloud.aiplatform.v1.SpecialistPoolService/GetSpecialistPool",
      type: GRPCCallType.unary
    )

    public static let listSpecialistPools = GRPCMethodDescriptor(
      name: "ListSpecialistPools",
      path: "/google.cloud.aiplatform.v1.SpecialistPoolService/ListSpecialistPools",
      type: GRPCCallType.unary
    )

    public static let deleteSpecialistPool = GRPCMethodDescriptor(
      name: "DeleteSpecialistPool",
      path: "/google.cloud.aiplatform.v1.SpecialistPoolService/DeleteSpecialistPool",
      type: GRPCCallType.unary
    )

    public static let updateSpecialistPool = GRPCMethodDescriptor(
      name: "UpdateSpecialistPool",
      path: "/google.cloud.aiplatform.v1.SpecialistPoolService/UpdateSpecialistPool",
      type: GRPCCallType.unary
    )
  }
}

